### ISSUE TITLE
[Feat.Req] subcommands

### ISSUE THREAD

**Issue by hopeyen** [graphops/one-shot-cli#8]
**Problem statement**

After renaming one-shot-cli to graphcast-cli, we can consider a boarder scope for what the CLI can do

**Expectation proposal**

- [ ] move sending upgrade intent message into a subcommand `graphcast send upgradeIntentMessage subgraph_id ...`
- [ ] add simple commands relevant to upgrade presync functionality
  - [ ] query a list of indexers who has active allocation for the existing subgraph deployment
  - [ ] get public status APIs for a list of indexers
  - [ ] query `indexingStatus` from the public status APIs for the new deployment
  - [ ] summarize status
